use std::{fs, path::Path};

use anyhow::{Context, Result};

use crate::memory::MemoryPaths;

pub fn build_system_prompt() -> String {
    BASE_INSTRUCTIONS.trim().to_owned()
}

pub fn build_runtime_reminder(
    workspace: &Path,
    skill_catalog: &str,
    memory: Option<&MemoryPaths>,
    additional_instructions: Option<&str>,
) -> Result<String> {
    let mut sections = vec![format!(
        "<environment>\nworkspace: {}\n</environment>",
        workspace.display()
    )];

    let agents_path = workspace.join("AGENTS.md");
    if agents_path.is_file() {
        let agents = fs::read_to_string(&agents_path)
            .with_context(|| format!("failed to read {}", agents_path.display()))?;
        sections.push(format!(
            "<project-instructions source=\"AGENTS.md\">\n{}\n</project-instructions>",
            agents.trim()
        ));
    }

    if !skill_catalog.trim().is_empty() {
        sections.push(format!(
            "<available-skills>\n{}\n</available-skills>",
            skill_catalog.trim()
        ));
    }

    if let Some(memory) = memory {
        sections.push(format!(
            "<memory>\n{}\n</memory>",
            memory.runtime_reminder_section()
        ));
    }

    if let Some(instructions) = additional_instructions.filter(|value| !value.trim().is_empty()) {
        sections.push(format!(
            "<task-instructions>\n{}\n</task-instructions>",
            instructions.trim()
        ));
    }

    Ok(format!(
        "<runtime-reminder>\n{}\n</runtime-reminder>",
        sections.join("\n\n")
    ))
}

const BASE_INSTRUCTIONS: &str = include_str!("../../prompts/agents/system.md");

#[cfg(test)]
mod tests {
    use std::fs;

    use tempfile::tempdir;

    use super::*;

    #[test]
    fn keeps_dynamic_context_out_of_the_system_prompt() {
        let directory = tempdir().unwrap();
        fs::write(directory.path().join("AGENTS.md"), "Run cargo test.").unwrap();
        let memory = MemoryPaths::new("/pico-home", directory.path());

        let system = build_system_prompt();
        let reminder = build_runtime_reminder(
            directory.path(),
            "- review: Review code",
            Some(&memory),
            Some("Focus on the delegated scope."),
        )
        .unwrap();

        assert_eq!(
            system,
            include_str!("../../prompts/agents/system.md").trim()
        );
        assert!(system.contains("<runtime-reminder>"));
        assert!(!system.contains("Run cargo test."));
        assert!(!system.contains("review: Review code"));
        assert!(!system.contains(directory.path().to_string_lossy().as_ref()));

        assert!(reminder.starts_with("<runtime-reminder>\n<environment>"));
        assert!(reminder.contains("<project-instructions source=\"AGENTS.md\">"));
        assert!(reminder.contains("Run cargo test."));
        assert!(reminder.contains("<available-skills>\n- review: Review code"));
        assert!(reminder.contains("<memory>"));
        assert!(reminder.contains("<task-instructions>"));
        assert!(reminder.ends_with("</runtime-reminder>"));
        assert!(!reminder.contains("generated by picoagent"));
    }
}
